### ISSUE TITLE
PeHeaderWhitelister: Crashes on "could not read ..."

### ISSUE THREAD

**Issue by targodan** [fkie-cad/RoAMer#4]
When executing `PeHeaderWhitelister.exe C:\` I got the following error:

```
could not read  C:\Users\User\AppData\Local\Microsoft\WindowsApps\GameBarElevatedFT_Alias.exe ... continuing
Traceback (most recent call last):
  File "whitelister\PeHeaderWhitelister.py", line 91, in <module>
  File "whitelister\PeHeaderWhitelister.py", line 80, in generate_pe_header_whitelist
  File "whitelister\PeHeaderWhitelister.py", line 68, in add_entry
  File "whitelister\PeHeaderWhitelister.py", line 45, in normalize_pe_header
  File "c:\program files\python38\lib\re.py", line 248, in finditer
    return _compile(pattern, flags).finditer(string)
TypeError: expected string or bytes-like object
[2420] Failed to execute script PeHeaderWhitelister
```

It's unclear why the file cannot be read (I am executing PeHeaderWhitelister as admin) but since the message says `could not read [...] ... continuing` I would expect the tool to continue. However it crashes immediately after.

I also deleted that file and tried again, in which case the same message came with a different file, followed by the same traceback and crash.

I'm running this on the Windows 10 x64 evaluation VM provided by microsoft. Python is version 3.8.

**Comment by UrmelAusDemEis** [comment]
Hello! 

Thank you very much for your feedback. This is a legit bug and I fixed it in [commit](https://github.com/fkie-cad/RoAMer/commit/a7bac497d7b8ee674e371d336e2efa97ad27a173)
