### ISSUE TITLE
main.exe crashes after writing files with "No module named win32con"

### ISSUE THREAD

**Issue by targodan** [fkie-cad/RoAMer#6]
This might just be a case of the docs needing clarification.

### How to reproduce

- I installed python 3.8 on windows 7 x64 Ultimate
- Installed dependencies via `pip install pyinstaller pywin32`
- Applied workaround mentioned in issue #5 
- Ran main.exe according to README (including the shortcut magic)
- Ran main.py from host

### Error output

VM:

```
2020-08-14 10:23:38,741 waiting...
2020-08-14 10:25:29,444 received needed files
2020-08-14 10:25:29,897 received everything
2020-08-14 10:25:29,913 writing files...
Traceback (most recent call last):
  File "unpacker\main.py", line 5, in <module>
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\PyInstaller\
loader\pyimod03_importers.py", line 623, in exec_module
  File "unpacker\Orchestrator.py", line 8, in <module>
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\PyInstaller\
loader\pyimod03_importers.py", line 623, in exec_module
  File "unpacker\Unpacker.py", line 6, in <module>
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\PyInstaller\
loader\pyimod03_importers.py", line 623, in exec_module
  File "unpacker\dumping\dumper.py", line 5, in <module>
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\PyInstaller\
loader\pyimod03_importers.py", line 623, in exec_module
  File "unpacker\dumping\dump_task.py", line 1, in <module>
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\PyInstaller\
loader\pyimod03_importers.py", line 623, in exec_module
  File "unpacker\winwrapper\utilities.py", line 8, in <module>
ModuleNotFoundError: No module named 'win32con'
[2916] Failed to execute script main
Traceback (most recent call last):
  File "main.py", line 82, in <module>
  File "main.py", line 78, in main
  File "main.py", line 73, in run
  File "WindowsManipulator.py", line 39, in grant_debug_privilege
TypeError: not all arguments converted during string formatting
[2896] Failed to execute script main
```

Host:

```
2020-08-14 10:50:04,221 Unpacking [path redacted]
2020-08-14 10:50:04,255 preparing VM for RoAMer
2020-08-14 10:50:10,344 VM Win7Ultimate should now be running on snapshot RoAMer
('[ip redacted]', 10000)
2020-08-14 10:50:10,344 Connecting to roamer-receiver...
2020-08-14 10:50:10,350 Sending file list...
2020-08-14 10:50:10,350 waiting for needed files...
b'both_EM0_sleep.dll,EP_EM0_sleep.dll,main.exe,TP_EM0_sleep.dll'
2020-08-14 10:50:10,356 start sending
2020-08-14 10:50:10,792 sending of unpacker completed.
2020-08-14 10:50:10,792 waiting for connection
```

**Comment by UrmelAusDemEis** [comment]
There is a compatibility issue with pyinstaller and python3.8.
